import = ["~/dotfiles/zenbones_light.toml"]

[font]
size = 16

[font.normal]
family = "Hack Nerd Font Mono"

[window]
decorations = "none"

[window.padding]
x = 7
y = 0

[env]
TERM = "xterm-256color"
