# Alacritty Color Scheme matching custom Neovim theme

[colors]

[colors.primary]
background = "#282828" # bg
foreground = "#ebdbb2" # fg

[colors.cursor]
text = "#ebdbb2"   # fg
cursor = "#C4CACF" # Custom cursor color

[colors.normal]
black = "#282828"   # Using bg for black
red = "#fb4934"     # rose
green = "#b8bb26"   # leaf
yellow = "#fabd2f"  # wood
blue = "#83a598"    # water
magenta = "#d3869b" # blossom
cyan = "#83c07c"    # sky
white = "#ebdbb2"   # fg

[colors.bright]
black = "#403833"   # Adjusted darker version of bg for bright black
red = "#fb4934"     # rose
green = "#b8bb26"   # leaf
yellow = "#fabd2f"  # wood
blue = "#83a598"    # water
magenta = "#d3869b" # blossom
cyan = "#83c07c"    # sky
white = "#ebdbb2"   # fg
